---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#  producer:
#    build: ./producer
#    image: producer:latest
#    ports:
#      - "8081:8081"
#    depends_on:
#      - broker
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
#
#  consumer:
#    build: ./consumer
#    image: consumer:latest
#    ports:
#      - "8082:8082"
#    depends_on:
#      - broker
#    environment:
#      SERVER_PORT: 8082
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092